### ISSUE TITLE
Cannot resolve partial name

### ISSUE THREAD

**Issue by stefandevo** [NetCoreTemplates/mvcauth#1]
https://github.com/NetCoreTemplates/mvcauth/blob/bce981ba2bbc21049bfb34bd6e65e26413a0c0f4/MyApp/Views/Account/Index.cshtml#L7

This gives "cannot resolve partial name"

**Comment by mythz** [comment]
Which page is giving you this error? Not seeing where this used and building/publishing is working without error.

**Comment by stefandevo** [comment]
Correct, there is no build/publishing error, my Rider IDE points towards it as a missing/unresolved partial name.
![image](https://user-images.githubusercontent.com/1656051/69652346-cde66a00-1071-11ea-8e9a-115519bf6e6d.png)
If this has no function, maybe you can remove it?

**Comment by mythz** [comment]
> If this has no function, maybe you can remove it?

Yep that's what I wanted to do, just wanted to confirm that you weren't seeing this error in a valid page. Resolved in this commit: https://github.com/NetCoreTemplates/mvcauth/commit/6a17887a68fc0974b67ebaf83dbff5985eaa94d2
